name: grover

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build and push image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u aberhrml --password-stdin
        docker build . --file grover/Dockerfile --tag ghcr.io/aberhrml/grover:latest
        docker push ghcr.io/aberhrml/grover:latest
