name: xcms-r build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:

   build_and_publish:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build and push image
      run: docker login --username aberhrml --password ${{ secrets.GH_PAT }} ghcr.io
      run: docker build . --file xcms-r/Dockerfile --tag xcms-r:latest
      run: docker push ghcr.io/aberhrml/xcms-r:atest

  
