name: xcms-r build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file xcms-r/Dockerfile --tag xcms-r
    
    - name: Push image
      run: |
        IMAGE_ID=ghcr.io/aberhrml/xcms-r
        VERSION=${{ steps.date.outputs.date }}
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag xcms-r $IMAGE_ID:$VERSION
        docker tag xcms-r $IMAGE_ID:latest
        docker push $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:latest
